from __future__ import annotations

import datetime as dt
from typing import Protocol

from ton_steward.payments.domain.models import PaymentSession


class PaymentRepository(Protocol):
    def next_id(self) -> str: ...
    def find_by_id(self, session_id: str) -> PaymentSession | None: ...
    def find_pending_by_user_id(self, user_id: int) -> list[PaymentSession]: ...
    def save(self, session: PaymentSession) -> None: ...
    def update(self, session: PaymentSession) -> None: ...
    def list_expired(self, now: dt.datetime) -> list[PaymentSession]: ...


class PaymentProvider(Protocol):
    """
    Interface for on-chain/network provider.
    """
    def check_transaction(self, *, tx_hash: str, expected_amount: float, expected_currency: str) -> bool: ...
    def get_payment_link(self, *, session: PaymentSession) -> str: ...
